src/lib/buy.ts

If you don't add a `-p` 
```bash
$ sf buy -i h100i
No one is selling this right now. To ask someone to sell it to you, add a price you're willing to pay. For example:
sf buy -i h100i -d "1h" -n 1 -p "$2.50" 
```

Add the ability to buy without using `-p` 

---

src/helpers/errors.ts
src/lib/ssh.ts

This is an alternative setup path to using `--add` so that a customer can just run:
```bash
sf ssh --init
sf ssh node-01
```
and it should just always work. I hope that the backend deduplicates ssh public keys as otherwise I can easily see customers running `--init` more than once and having the backend receive another request to add it.
I was slightly unsure about the expected handling of errors in terms of what should be logged, thrown, etc. but I have tested this code somewhat thoroughly manually and it seems to work properly from everything that I can observe. I probably made it more robust than necessary, but also I really don't want to debug weird edge cases of this command failing while a customer is stressed and unable to ssh into their machines. I was wondering if should update …

ssh add --init flag

---

install.sh

We could also change `curl -fsSL https://sfcompute.com/cli/install | bash` to `curl -fsSL https://sfcompute.com/cli/install | sh`.

improve install

---

install.sh

Same as v1 but without the `mv` to `mv -T` change. I guess that `shellcheck` didn't catch that issue. I tested it this time on an AWS macOS machine and it seemed to work.

improve install v2

---

src/lib/buy.ts

Tested locally, works. 
You can do:
`sf buy -colo cont_xyz`
or 
`sf buy -colo cont_abc, cont_xyz`
`-colo` is short for `--colocate_with`

Colocation option when buying

---

src/lib/updown.tsx

This cleans up a lot of the logic that was somewhat hard to follow, and had bugs such as dividing by 8 twice instead of once (so the number of nodes seemed wrong). The user feedback was also somewhat confusing, hopefully it is slightly less confusing.
There are still a few bugs such as the minimum duration seeming to be a bit wonky as when I request a minimum of 1 hour it seems that the backend purchased 2, but maybe that is expected from rounding (I would have to think about it more). More importantly, it seems to misuse the quoted price so that for example one runs `deno run prod up -d 1m -p 2.8` then it will quote the rest of the hour (fine), but then it will use that to determine the maximum price to pay for future hours (not fine). Also I remember the command working right away in …

updown: bug fixes

---

.cursor/rules/cli.mdc
.github/workflows/ci.yml
deno.json
deno.lock
src/checkVersion.ts
src/helpers/config.ts
src/helpers/errors.ts
src/helpers/feature-flags.ts
src/helpers/units.ts
src/helpers/urls.ts
src/helpers/waitingForOrder.ts
src/index.ts
src/lib/balance.ts
src/lib/buy/index.tsx
src/lib/clusters/clusters.tsx
src/lib/contracts/index.tsx
src/lib/dev.ts
src/lib/login.ts
src/lib/me.ts
src/lib/orders/index.tsx
src/lib/posthog.ts
src/lib/sell/index.tsx
src/lib/tokens.ts
src/lib/upgrade.ts
src/lib/vm.ts
src/scripts/release.ts
src/types/deno.d.ts

Fixes the error where a user sets an explicit duration for a buy order, and it doesn't end on an hour boundary. Rounds the end time/duration up to the next hour boundary.

fix: [ENG-1319] allow user to set explicit `end` time, round up `end` and `duration` to the nearest hour

---

.cursor/rules/copywriting.mdc
.cursor/rules/guidelines.mdc

This commit introduces two new markdown files: `copywriting.mdc` and `guidelines.mdc`. The `copywriting.mdc` file outlines rules for writing clear, concise, and user-centered copy, while the `guidelines.mdc` provides essential design principles and behaviors for CLI tools, focusing on human-first design, consistency, and effective error handling. These documents aim to enhance user experience and ensure clarity in communication across the application.

Add copywriting and design guidelines for improved user communication

---

src/lib/vm.ts

- **vm.ts: rm unused order param**
- **vm.ts: rm params.append(before|since) - it has no effect**

vms/logs: rm params.append(before|since) - it has no effect

---

src/checkVersion.ts

Added a check to skip the auto-upgrade process if the environment variable SF_CLI_DISABLE_AUTO_UPGRADE is set. This allows users to control the upgrade behavior of the CLI more effectively.

feat: disable auto-upgrade based on environment variable

---

src/lib/ssh.ts

I was annoyed that I kept seeing the same
```text
The authenticity of host '[64.78.177.245]:2479' can't be established.
ED25519 key fingerprint is SHA256:3Q/ZMffE4IaRCX3D2TzFDTA1h33fzopmFA7Rq2Mi1vk.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```
prompt as it would rotate through the multiple proxy IPs. This small change fixes that by using a consistent value to look up in the ~/.ssh/known_hosts file.
It does not appear that `CheckHostIP=no` is needed.

consistent ssh known_hosts value with multiple proxies

---

src/lib/clusters/clusters.tsx

We were using Bade to show the contract id.
However, badge turns everything to upper case.
This is a problem as our contract ids are base62 encoded - where the
distinction between lower case and upper case matters.

fix(cluster): output of cluster ls now shows the correct contract id

---

src/index.ts
src/lib/contracts/index.tsx

- **fix(contracts): output well formed json from --json flag**
- **feat(cli): if json flag is specified do not display app banner or nudge users to upgrade**

Fix json mode

---

src/lib/buy/index.tsx

Since we're single threaded, it is possible that:
- we setLoading(false)
- this updates the component rendered (however, at this point we haven't
set quote yet)
- So we tell the user that there's no quote
- then the if (quote) setQuote(quote) runs
- TUI updtes to reflect the quote.
From the users point of view we've told them there's no quote and
immediately given them a quote.
In this commit we setQuote before setLoading so they don't see this ui
blip.

fix(quote): setQuote before we setLoading = false

---

src/lib/vm.ts

It doesn't work as intended as is going to refactored.

remove instance_group_id

---

.github/workflows/ci.yml
src/lib/buy/index.tsx
src/lib/clusters/mock.ts
src/lib/scale/create.tsx
src/lib/scale/index.tsx
src/lib/scale/list.tsx
src/lib/scale/update.tsx
src/lib/sell/index.tsx

Updates `sf scale` command and subcommands to follow https://clig.dev/#help.
Adds examples to `sf scale`, `sf scale create`, `sf scale update`, and `sf scale list`.
Makes `sf list` gracefully fail.
Also makes `sf scale` and `sf buy` display help text on error. This makes them follow "Display help text when passed no options".

feat: [PRODUCT-347] add better examples to the help text for sf scale

---

src/helpers/instance-types-meta.ts
src/lib/buy/index.tsx

- Introduced a new helper file `instance-types-meta.ts` containing metadata for instance types.
- Updated `BuyOrderPreview` component to display a user-friendly label for the instance type based on the new metadata.

feat: add instance type metadata and update BuyOrderPreview component

---

src/lib/contracts/ContractDisplay.tsx

Added support for displaying instance type metadata in the ContractDisplay component. The instance type is now shown with a label if it is supported, improving clarity for users.

feat: enhance ContractDisplay to include instance type metadata display

---

src/lib/Row.tsx
src/lib/scale/ConfirmationMessage.tsx
src/lib/scale/ProcurementDisplay.tsx
src/lib/scale/list.tsx

`sf scale create`
`sf scale ls`
`sf scale update`

feat: [PRODUCT-409] show human friendly instance type in `sf scale`

---

src/lib/clusters/clusters.tsx

Vaid vcluster credentials were being marked as not ready by the CLI and a customer noticed it:
https://sfcompute.slack.com/archives/C079B9UE2LE/p1750872799183859
Modified the `is_usable` boolean check in the `listClusterUsers` function to consider a cluster as usable if it's a vcluster type with encrypted_kubeconfig, nonce, and ephemeral_pubkey properties.

fix: vcluster credentials verification logic

---

src/lib/vm.ts

Reimplement `vm logs` using `v0/logs2` instead of `v0/logs`.

refactor: [PRODUCT-465] use `logs2` instead of `logs` REST endpoint

---

src/lib/vm.ts

When a VM is awaiting scheduling:
When a user has a VM less than 10 minutes old:
Additionally, adds `--json` flag support.

feat: [PRODUCT-503] [PRODUCT-504] show helpful messages during VM scheduling and startup

---

src/lib/scale/ProcurementDisplay.tsx
src/lib/scale/update.tsx

Customer reported an issue where `disabled` procurements (procurements disabled using the API) do not render as `disabled` in `sf procurements ls`

fix: support explicitly `disabled` procurements

---

src/lib/nodes/create.ts
src/lib/nodes/extend.ts
src/lib/nodes/index.ts
src/lib/nodes/list.tsx
src/lib/nodes/release.ts
src/lib/nodes/set.ts
src/lib/nodes/utils.ts

- Context-aware recommendations - Different command suggestions based on node type (spot nodes get sf nodes set suggestions instead of sf nodes extend)

feat: [PRODUCT-545] educate the user about Nodes -> VMs + other iteration

---

src/lib/nodes/create.ts

Because the way we construct the quote in `sf buy` and `sf nodes` is subtly different, sometimes `sf nodes` will fail to find a quote whereas `sf buy` will, as `sf nodes` does not round start times.
```bash
sf nodes create test-node-5 --zone hayesvalley --start "+24h" --duration 1h --max-price 30.00
No nodes available matching your requirements. This is likely due to insufficient capacity.
```
```bash
sf nodes create test-node-5 --zone hayesvalley --start "+5h" --duration 1h --max-price 30.00
No nodes available matching your requirements. This is likely due to insufficient capacity.
```
Solution: round start times.

fix: [ENG-2207] wiggle quote start time to land on an hour boundary

---

src/lib/nodes/create.ts
src/lib/nodes/utils.ts

> The CLI should delineate clearly between these two types of Nodes Auto-Reserved vs Reservation.
> 
> Folks using auto nodes should understand that we will continue to buy time on their behalf and spin nodes up and down.
> 
> Additionally, when using auto nodes users should be ok with their vm being interrupted.
> 
> I think we want to drill into users heads that these are two separate concepts for different use cases

feat: [ENG-2165] add --reserved and --auto flags to sf nodes create

---

src/helpers/units.ts
src/lib/buy/index.tsx
src/lib/scale/create.tsx

Edge case: when the order's duration is very short, the displayed rate is wrong. The reason why it's wrong is that the market treats the string `"NOW"` as "the beginning of the next minute", not `new Date()`. 
This PR fixes it by handling this explicitly in `getPricePerGpuHourFromQuote`
```
sf buy -d 1m -t h200ki
Automatically upgrading 0.19.12 → 0.19.13
✔ Downloading install script
✔ Upgrade completed successfully
☁️☁️☁️
start  aug 27 5:55 pm (now)
end    aug 27 6:00 pm (in 5 minutes)
dur    ~5m
size   8 gpus
type   Kubernetes (h200ki)
rate   ~$1.86/gpu/hr
total  $1.12
Place order? (y/n)  
sf buy -d 1h -t h200ki
start  aug 27 5:55 pm (now)
end    aug 27 7:00 pm (in an hour)
dur    ~1h
size   8 gpus
type   Kubernetes (h200ki)
rate   ~$2.10/gpu/hr
total  $17.92
Place order? (y/n)  
```

fix(buy): fix bug in rate display logic

---

src/lib/buy/index.tsx

Sometimes `sf buy` re-enters its poll loop after the order is already filled. If `GET /v0/orders` fails when that occurs, `sf buy` will error out, even though the order successfully filled.
This PR attempts to fix this by doing two things:
1. Use a recursive `setTimeout` instead of a `setInterval`. That way, there will only ever be one poll happening at a time, which prevents redundant polls (the call to `exit()` will happen before the `useEffect` is re-run) 
2. use `order?.id` as the dependency to the `useEffect`, not `order`. This will prevent the `useEffect` from being run after calling `setOrder(o)`, because the order ID will be the same.

fix: fix race condition in poll loop

---

src/lib/nodes/create.ts

Without the duration and name the command will fail when users try to
copy paste it.

fix(nodes/create): Add duration to first example
