biome.json, src/index.ts, src/lib/balance.ts, src/lib/dev.ts, src/lib/instances.ts
> populated
> 
> <img width="500" alt="Screenshot 2024-07-24 at 10 43 32 PM" src="https://github.com/user-attachments/assets/bf26dfcd-401f-45f7-b816-56e7dd12e0eb">
> 
> 
> empty state
> 
> <img width="500" alt="populated" src="https://github.com/user-attachments/assets/91d2015b-e787-41a2-91b6-eaf3d4dc6b66">
=> sf instances ls

src/helpers/errors.ts, src/helpers/urls.ts, src/lib/buy.ts, src/lib/dev.ts, src/lib/orders.ts
=> sf orders cancel <id>

install.sh
=> fix arch detection for arm mac

install.sh
=> Revert "improve install"

package.json, src/lib/clusters/clusters.tsx
- Enhance cluster list rendering with more structured Row components
- Add handling for empty cluster list with guidance to user
- Minor code cleanup and import reorganization
=> Improve cluster list display and handling

src/lib/buy/index.tsx
This commit introduces a new option `--standing` to the buy command, allowing users to place standing orders instead of the default market orders. The help text and examples have been updated to reflect this addition, enhancing the functionality and user experience when placing buy orders.
=> Add standing order option to buy command

src/lib/login.ts
=> login: generate verification string with with crypto.randomInt instead of math.random

src/lib/vm.ts
We also update the default value of limit from 50 to 100.
=> feat(vm/logs): add examples

install.sh
Now the terminal won't be green after install.
=> fix colors

src/index.ts, src/lib/posthog.ts, src/lib/scale.tsx, src/schema.ts
https://github.com/user-attachments/assets/7f22434b-074e-47a2-85ce-3a289f8dde2e
=> feat: [TRADE-233] re-implement `sf scale` using new `v0/procurements` route

src/lib/scale/create.tsx, src/lib/scale/index.tsx, src/lib/scale/list.tsx, src/lib/scale/update.tsx
Follow up to #139, following #95
=> chore: [PRODUCT-347] capitalize option text (including help)

src/lib/clusters/clusters.tsx
Until org accounts are reworked, we are silencing the error for failing to decrypt tokens:
Context:
https://sfcompute.slack.com/archives/C080PSH54JZ/p1746470002132789
Local testing shows no more decryption errors
=> Silencing Decryption Error 

src/lib/clusters/clusters.tsx
Improves the error message given when we fail to decode any k8s creds - an unexpected error.
=> K8s credentials error message fix 

deno.lock, package.json, src/lib/login.ts, src/lib/me.ts
This reverts commit 23aed1f5909d2e7492c682ba5b58500be6cca089.
=> revert: "feat: [PRODUCT-372] add `--token` option to `sf login` (#145)"

src/lib/clusters/clusters.tsx, src/lib/clusters/credentialTypes.ts, src/schema.ts
=> fix: [ENG-1791] regenerate `schema.ts` using unified `api.sfcompute.com` root OpenAPI schema

src/helpers/instance-types-meta.ts, src/schema.ts
Adds support for buying `h200` instances in the CLI.
=> chore: [PRODUCT-431] support quoting/buying H200 instances

deno.lock, src/index.ts
Posthog client was hanging on `process.exit()`. Forcefully shut it down.
=> fix: [PRODUCT-543] explicitly shutdown Posthog client

src/lib/nodes/create.ts, src/lib/nodes/index.ts
Updated examples:
```bash
Examples:
$ sf nodes create my-node-name --zone hayesvalley --max-price 12.50
$ sf nodes create -n 2 -z hayesvalley --start +1h --duration 2d -p 15.00
$ sf nodes list
$ sf nodes release my-node-name
$ sf nodes set my-node-name --max-price 12.50
$ sf nodes extend my-node --duration 3600 --max-price 12.50
```
=> chore: [PRODUCT-550] update sf nodes root and create examples

deno.lock, package.json, src/helpers/format-date.ts, src/helpers/units.ts, src/lib/nodes/create.ts, src/lib/nodes/extend.ts, src/lib/nodes/utils.ts
https://github.com/user-attachments/assets/0498f101-c0cf-4f6a-8468-2f1add9f45f7
=> fix: [PRODUCT-592] allow users to round relative times/durations in `sf nodes`

deno.lock, package.json, src/lib/nodes/create.ts, src/lib/nodes/redeploy.ts
Changing to `base64` from `number[]` to make this more clear
=> feat: [PRODUCT-588] `user_data` is encoded as `base64` binary file
